plugins {
    alias(libs.plugins.jetbrains.kotlin.jvm)
}

dependencies {
    implementation libs.kotlinx.coroutines.core
    implementation libs.okhttp
    implementation libs.json
    implementation libs.sqlite.jdbc
}

tasks.register('runGenerator', JavaExec) {
    group = 'tools'
    description = 'Runs HadeethEncGenerator'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.alquranplus.tools.HadeethEncGenerator'
}
